import React, { useState } from "react";

const SEARCH = {
  searchTerm: "",
  location: "",
};
const FILTERS = [
  { name: "all" },
  { name: "full-time" },
  { name: "part-time" },
  { name: "remote" },
];
export const jobs = [
  {
    id: 1,
    title: "Frontend Developer",
    description: "Build responsive UI with React and Bootstrap.",
    type: "full-time",
    location: "Abuja",
    min_salary: 500000,
    max_salary: 800000,
    company_name: "TechNova",
    created_at: "2026-06-10",
    poster_id: 2,
  },
  {
    id: 2,
    title: "Backend Engineer",
    description: "Develop REST APIs using Node.js and Express.",
    type: "full-time",
    location: "Lagos",
    min_salary: 700000,
    max_salary: 1200000,
    company_name: "CloudCore",
    created_at: "2026-06-11",
    poster_id: 3,
  },
  {
    id: 3,
    title: "UI/UX Designer",
    description: "Design clean user interfaces and improve UX flows.",
    type: "contract",
    location: "Remote",
    min_salary: 400000,
    max_salary: 700000,
    company_name: "PixelCraft",
    created_at: "2026-06-09",
    poster_id: 2,
  },
  {
    id: 4,
    title: "Full Stack Developer",
    description: "Work on both frontend and backend systems.",
    type: "full-time",
    location: "Abuja",
    min_salary: 800000,
    max_salary: 1500000,
    company_name: "StackBridge",
    created_at: "2026-06-08",
    poster_id: 4,
  },
  {
    id: 5,
    title: "DevOps Engineer",
    description: "Manage CI/CD pipelines and cloud infrastructure.",
    type: "full-time",
    location: "Remote",
    min_salary: 1000000,
    max_salary: 1800000,
    company_name: "InfraSync",
    created_at: "2026-06-07",
    poster_id: 3,
  },
  {
    id: 6,
    title: "Product Manager",
    description: "Lead product development and roadmap planning.",
    type: "full-time",
    location: "Lagos",
    min_salary: 900000,
    max_salary: 1600000,
    company_name: "Buildify",
    created_at: "2026-06-06",
    poster_id: 5,
  },
  {
    id: 7,
    title: "Mobile App Developer",
    description: "Build cross-platform apps using React Native.",
    type: "contract",
    location: "Remote",
    min_salary: 600000,
    max_salary: 1100000,
    company_name: "AppForge",
    created_at: "2026-06-05",
    poster_id: 4,
  },
  {
    id: 8,
    title: "Data Analyst",
    description: "Analyze datasets and generate insights.",
    type: "part-time",
    location: "Abuja",
    min_salary: 300000,
    max_salary: 600000,
    company_name: "DataLens",
    created_at: "2026-06-04",
    poster_id: 2,
  },
  {
    id: 9,
    title: "Technical Writer",
    description: "Write technical documentation for software products.",
    type: "contract",
    location: "Remote",
    min_salary: 250000,
    max_salary: 500000,
    company_name: "DocuFlow",
    created_at: "2026-06-03",
    poster_id: 5,
  },
  {
    id: 10,
    title: "Cybersecurity Analyst",
    description: "Monitor systems and prevent security threats.",
    type: "full-time",
    location: "Lagos",
    min_salary: 1100000,
    max_salary: 2000000,
    company_name: "SecureNet",
    created_at: "2026-06-02",
    poster_id: 3,
  },
];
export const useFilters = () => {
  const [searchForm, setSearchForm] = useState(SEARCH);

  return { searchForm, setSearchForm, SEARCH, FILTERS, jobs };
};
